teamAbbrev <- function(team){
  ab <- switch(team,
                "Atlanta Hawks" = 'ATL',
                "Boston Celtics" = 'BOS',
                "Brooklyn Nets" = 'BKN',
                "Charlotte Bobcats" = 'CHA',
                "Chicago Bulls" = 'CHI',
                "Cleveland Cavaliers" = 'CLE',
                "Dallas Mavericks" = 'DAL',
                "Denver Nuggets" = 'DEN',
                "Detroit Pistons" = 'DET',
                "Golden State Warriors" = 'GSW', 
                "Houston Rockets" = 'HOU',
                "Indiana Pacers" = 'IND',
                "Los Angeles Clippers" = 'LAC',
                "Memphis Grizzlies" = 'MEM',
                "Miami Heat" = 'MIA',
                "Milwaukee Bucks" = 'MIL',
                "Minnesota Timberwolves" = 'MIN',
                "New Orleans Hornets" = 'NOH',
                "New York Knicks" = 'NYK',
                "Oklahoma City Thunder" = 'OKC',
                "Orlando Magic" = 'ORL', 
                "Philadelphia 76ers" = 'PHI',
                "Phoenix Suns" = 'PHO',
                "Portland Trail Blazers" = 'POR', 
                "Sacramento Kings" = 'SAC', 
                "San Antonio Spurs" = 'SAS',
                "Torontor Raptors" = 'TOR',
                "Utah Jazz" = 'UTA',
                "Washington Wizards" = 'WAS'  )  
  
  ab
}